name: Lint and test

on: [push]

jobs:
  LintAndTest:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        npm i
        npm i -g truffle
        npm i eslint
    - name: Run Ganache on Docker image
      run: docker run -d -p 8545:8545 trufflesuite/ganache-cli -f https://mainnet.infura.io/v3/2c9885dfbf00441393ec7afae72363d5 --unlock "0xc0a47dFe034B400B47bDaD5FecDa2621de6c4d95" --unlock "0x6B175474E89094C44Da98b954EedeAC495271d0F" --unlock "0x2a1530C4C41db0B0b2bB646CB5Eb1A67b7158667" --unlock "0x98CC3BD6Af1880fcfDa17ac477B2F612980e5e33" --unlock "0xdfbaf3e4c7496dad574a1b842bc85b402bdc298d" --unlock "0xA6923533A6362008e9b536271C2Bdc0FF1467D3c"
    - name: Lint
      run: npm run lint:nofix
    - name: Test
      run: npm run test
      env:
        CI: true
