name: Lint and test

on: [push]

jobs:
  LintAndTest:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.7.0]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        npm i
        npm i -g truffle
        npm i eslint
        npm i solhint
    - name: Run Ganache on Docker image
      run: docker run -d -p 8545:8545 trufflesuite/ganache-cli -f https://mainnet.infura.io/v3/$INFURA_PROJECTID --unlock "0xc0a47dFe034B400B47bDaD5FecDa2621de6c4d95" --unlock "0x6B175474E89094C44Da98b954EedeAC495271d0F" --unlock "0x2a1530C4C41db0B0b2bB646CB5Eb1A67b7158667" --unlock "0x98CC3BD6Af1880fcfDa17ac477B2F612980e5e33" --unlock "0xdfbaf3e4c7496dad574a1b842bc85b402bdc298d" --unlock "0xfc9362c9aa1e4c7460f1cf49466e385a507dfb2b"
      env:
        INFURA_PROJECTID: 2c9885dfbf00441393ec7afae72363d5
    - name: Lint
      run: npm run lint:nofix
    - name: Test
      run: truffle test --network mainlocal
      env:
        CI: true